package org.qbook.utils

/** Bundled, offline-capable typefaces shipped with QBooK. */
object PredefinedFonts {
    data class Definition(val name: String, val asset: String, val category: String)
    val all: List<Definition> = listOf(
        Definition("Roboto", "font_000.woff2", "Sans Serif"),
        Definition("Open Sans", "font_001.woff2", "Sans Serif"),
        Definition("Poppins", "font_002.woff2", "Sans Serif"),
        Definition("Lato", "font_003.woff2", "Sans Serif"),
        Definition("Roboto Condensed", "font_004.woff2", "Sans Serif"),
        Definition("Roboto Mono", "font_005.woff2", "Monospace"),
        Definition("Arimo", "font_006.woff2", "Sans Serif"),
        Definition("Oswald", "font_007.woff2", "Sans Serif"),
        Definition("Raleway", "font_008.woff2", "Sans Serif"),
        Definition("DM Sans", "font_009.woff2", "Sans Serif"),
        Definition("Nunito", "font_010.woff2", "Sans Serif"),
        Definition("Nunito Sans", "font_011.woff2", "Sans Serif"),
        Definition("Playfair Display", "font_012.woff2", "Serif"),
        Definition("Roboto Slab", "font_013.woff2", "Serif"),
        Definition("Rubik", "font_014.woff2", "Sans Serif"),
        Definition("Ubuntu", "font_015.woff2", "Sans Serif"),
        Definition("Archivo Black", "font_016.woff2", "Sans Serif"),
        Definition("Kanit", "font_017.woff2", "Sans Serif"),
        Definition("Manrope", "font_018.woff2", "Sans Serif"),
        Definition("Outfit", "font_019.woff2", "Sans Serif"),
        Definition("Work Sans", "font_020.woff2", "Sans Serif"),
        Definition("Lora", "font_021.woff2", "Serif"),
        Definition("PT Sans", "font_022.woff2", "Sans Serif"),
        Definition("Figtree", "font_023.woff2", "Sans Serif"),
        Definition("Plus Jakarta Sans", "font_024.woff2", "Sans Serif"),
        Definition("Bebas Neue", "font_025.woff2", "Sans Serif"),
        Definition("Quicksand", "font_026.woff2", "Sans Serif"),
        Definition("Mulish", "font_027.woff2", "Sans Serif"),
        Definition("Prompt", "font_028.woff2", "Sans Serif"),
        Definition("Barlow", "font_029.woff2", "Sans Serif"),
        Definition("Source Sans 3", "font_030.woff2", "Sans Serif"),
        Definition("Black Ops One", "font_031.woff2", "Display"),
        Definition("Bricolage Grotesque", "font_032.woff2", "Sans Serif"),
        Definition("Saira", "font_033.woff2", "Sans Serif"),
        Definition("IBM Plex Sans", "font_034.woff2", "Sans Serif"),
        Definition("Inconsolata", "font_035.woff2", "Monospace"),
        Definition("Jost", "font_036.woff2", "Sans Serif"),
        Definition("Archivo", "font_037.woff2", "Sans Serif"),
        Definition("Karla", "font_038.woff2", "Sans Serif"),
        Definition("Heebo", "font_039.woff2", "Sans Serif"),
        Definition("JetBrains Mono", "font_040.woff2", "Monospace"),
        Definition("Share Tech", "font_041.woff2", "Sans Serif"),
        Definition("Smooch Sans", "font_042.woff2", "Sans Serif"),
        Definition("Fira Sans", "font_043.woff2", "Sans Serif"),
        Definition("Titillium Web", "font_044.woff2", "Sans Serif"),
        Definition("Space Grotesk", "font_045.woff2", "Sans Serif"),
        Definition("Source Code Pro", "font_046.woff2", "Monospace"),
        Definition("Google Sans Flex", "font_047.woff2", "Sans Serif"),
        Definition("PT Serif", "font_048.woff2", "Serif"),
        Definition("Libre Baskerville", "font_049.woff2", "Serif"),
        Definition("Fjalla One", "font_050.woff2", "Sans Serif"),
        Definition("Dancing Script", "font_051.woff2", "Handwriting"),
        Definition("Lobster Two", "font_052.woff2", "Display"),
        Definition("Libre Franklin", "font_053.woff2", "Sans Serif"),
        Definition("Barlow Condensed", "font_054.woff2", "Sans Serif"),
        Definition("Public Sans", "font_055.woff2", "Sans Serif"),
        Definition("Josefin Sans", "font_056.woff2", "Sans Serif"),
        Definition("Anton", "font_057.woff2", "Sans Serif"),
        Definition("Instrument Serif", "font_058.woff2", "Serif"),
        Definition("Changa One", "font_059.woff2", "Display"),
        Definition("Sora", "font_060.woff2", "Sans Serif"),
        Definition("Alfa Slab One", "font_061.woff2", "Display"),
        Definition("Assistant", "font_062.woff2", "Sans Serif"),
        Definition("Schibsted Grotesk", "font_063.woff2", "Sans Serif"),
        Definition("Inter Tight", "font_064.woff2", "Sans Serif"),
        Definition("Bitter", "font_065.woff2", "Serif"),
        Definition("Lexend", "font_066.woff2", "Sans Serif"),
        Definition("Cabin", "font_067.woff2", "Sans Serif"),
        Definition("Cairo", "font_068.woff2", "Sans Serif"),
        Definition("IBM Plex Mono", "font_069.woff2", "Monospace"),
        Definition("Fraunces", "font_070.woff2", "Serif"),
        Definition("Hind Siliguri", "font_071.woff2", "Sans Serif"),
        Definition("Urbanist", "font_072.woff2", "Sans Serif"),
        Definition("DM Serif Display", "font_073.woff2", "Serif"),
        Definition("Dosis", "font_074.woff2", "Sans Serif"),
        Definition("Lilita One", "font_075.woff2", "Display"),
        Definition("Red Hat Display", "font_076.woff2", "Sans Serif"),
        Definition("Noto Sans Khmer", "font_077.woff2", "Sans Serif"),
        Definition("Mukta", "font_078.woff2", "Sans Serif"),
        Definition("Instrument Sans", "font_079.woff2", "Sans Serif"),
        Definition("Rajdhani", "font_080.woff2", "Sans Serif"),
        Definition("Exo 2", "font_081.woff2", "Sans Serif"),
        Definition("Caveat", "font_082.woff2", "Handwriting"),
        Definition("Geist", "font_083.woff2", "Sans Serif"),
        Definition("Hind", "font_084.woff2", "Sans Serif"),
        Definition("Orbitron", "font_085.woff2", "Sans Serif"),
        Definition("Fredoka", "font_086.woff2", "Sans Serif"),
        Definition("Overpass", "font_087.woff2", "Sans Serif"),
        Definition("Oxygen", "font_088.woff2", "Sans Serif"),
        Definition("Crimson Text", "font_089.woff2", "Serif"),
        Definition("Bungee", "font_090.woff2", "Display"),
        Definition("Slabo 27px", "font_091.woff2", "Serif"),
        Definition("Pacifico", "font_092.woff2", "Handwriting"),
        Definition("Cinzel", "font_093.woff2", "Serif"),
        Definition("Tajawal", "font_094.woff2", "Sans Serif"),
        Definition("Barlow Semi Condensed", "font_095.woff2", "Sans Serif"),
        Definition("PT Sans Narrow", "font_096.woff2", "Sans Serif"),
        Definition("Lobster", "font_097.woff2", "Display"),
        Definition("Merriweather Sans", "font_098.woff2", "Sans Serif"),
        Definition("Arvo", "font_099.woff2", "Serif"),
        Definition("Domine", "font_100.woff2", "Serif"),
        Definition("Comfortaa", "font_101.woff2", "Display"),
        Definition("Noto Sans Thai", "font_102.woff2", "Sans Serif"),
        Definition("Abel", "font_103.woff2", "Sans Serif"),
        Definition("Teko", "font_104.woff2", "Sans Serif"),
        Definition("Hanken Grotesk", "font_105.woff2", "Sans Serif"),
        Definition("Newsreader", "font_106.woff2", "Serif"),
        Definition("Chakra Petch", "font_107.woff2", "Sans Serif"),
        Definition("Space Mono", "font_108.woff2", "Monospace"),
        Definition("Asap", "font_109.woff2", "Sans Serif"),
        Definition("Bodoni Moda", "font_110.woff2", "Serif"),
        Definition("Gravitas One", "font_111.woff2", "Display"),
        Definition("Zeyada", "font_112.woff2", "Handwriting"),
        Definition("DM Mono", "font_113.woff2", "Monospace"),
        Definition("Shadows Into Light", "font_114.woff2", "Handwriting"),
        Definition("Maven Pro", "font_115.woff2", "Sans Serif"),
        Definition("Zilla Slab", "font_116.woff2", "Serif"),
        Definition("ABeeZee", "font_117.woff2", "Sans Serif"),
        Definition("Questrial", "font_118.woff2", "Sans Serif"),
        Definition("Lexend Deca", "font_119.woff2", "Sans Serif"),
        Definition("Geist Mono", "font_120.woff2", "Monospace"),
        Definition("Abril Fatface", "font_121.woff2", "Display"),
        Definition("Alumni Sans", "font_122.woff2", "Sans Serif"),
        Definition("Onest", "font_123.woff2", "Sans Serif"),
        Definition("Play", "font_124.woff2", "Sans Serif"),
        Definition("Albert Sans", "font_125.woff2", "Sans Serif"),
        Definition("Satisfy", "font_126.woff2", "Handwriting"),
        Definition("Archivo Narrow", "font_127.woff2", "Sans Serif"),
        Definition("Rethink Sans", "font_128.woff2", "Sans Serif"),
        Definition("Exo", "font_129.woff2", "Sans Serif"),
        Definition("Marcellus", "font_130.woff2", "Serif"),
        Definition("Almarai", "font_131.woff2", "Sans Serif"),
        Definition("Be Vietnam Pro", "font_132.woff2", "Sans Serif"),
        Definition("Varela Round", "font_133.woff2", "Sans Serif"),
        Definition("IBM Plex Serif", "font_134.woff2", "Serif"),
        Definition("League Spartan", "font_135.woff2", "Sans Serif"),
        Definition("Spectral", "font_136.woff2", "Serif"),
        Definition("Great Vibes", "font_137.woff2", "Handwriting"),
        Definition("Syne", "font_138.woff2", "Sans Serif"),
        Definition("Cormorant", "font_139.woff2", "Serif"),
        Definition("IBM Plex Sans Arabic", "font_140.woff2", "Sans Serif"),
        Definition("Geologica", "font_141.woff2", "Sans Serif"),
        Definition("Sanchez", "font_142.woff2", "Serif"),
        Definition("Frank Ruhl Libre", "font_143.woff2", "Serif"),
        Definition("Indie Flower", "font_144.woff2", "Handwriting"),
        Definition("Permanent Marker", "font_145.woff2", "Handwriting"),
        Definition("Crimson Pro", "font_146.woff2", "Serif"),
        Definition("Epilogue", "font_147.woff2", "Sans Serif"),
        Definition("Kalam", "font_148.woff2", "Handwriting"),
        Definition("Noto Sans Tamil", "font_149.woff2", "Sans Serif"),
        Definition("Oleo Script", "font_150.woff2", "Display"),
        Definition("Saira Condensed", "font_151.woff2", "Sans Serif"),
        Definition("Sarabun", "font_152.woff2", "Sans Serif"),
        Definition("Sofia Sans", "font_153.woff2", "Sans Serif"),
        Definition("Encode Sans", "font_154.woff2", "Sans Serif"),
        Definition("Atkinson Hyperlegible", "font_155.woff2", "Sans Serif"),
        Definition("Fira Code", "font_156.woff2", "Monospace"),
        Definition("Vollkorn", "font_157.woff2", "Serif"),
        Definition("Alegreya Sans", "font_158.woff2", "Sans Serif"),
        Definition("Noto Kufi Arabic", "font_159.woff2", "Sans Serif"),
    )
}
